const CONSTANTS = {
  APP: 'app',
  EDIT: 'edit',
  TRAIN: 'train',
  NATIVE: 'native',
  LEARN: 'learn',
  DONE: 'Done',
  MAIN_FORM: 'mainForm',
  LIST_HEADING_PLACEHOLDER: 'List heading',
  CONFIRM_TEXT: 'Are you sure you want to delete this list?',
  FORM_DELETE_TITLE: 'Delete list',
  CLASS_NAMES: {
    FORM: 'form',
    FORM_DELETE: 'form-delete',
    FORM_TITLE: 'form-title',
    TEXTAREA_GROUP: 'form-item',
    FORM_TEXTAREA: 'form-textarea',
    BUTTON: 'btn',
    ADD_TEXTAREA_GROUP: 'add-item',
    LIST: 'list',
    LIST_ITEM: 'list-item',
  },
}